# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/cargi/Documents/1Fa26/SD/digilent-xdc-master/Zybo-Z7-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bclk_div_0_0/design_1_bclk_div_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_bclk_div_0_0 || ORIG_REF_NAME==design_1_bclk_div_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_delay_0_0/design_1_delay_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_delay_0_0 || ORIG_REF_NAME==design_1_delay_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_i2s_rx_0_0/design_1_i2s_rx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_i2s_rx_0_0 || ORIG_REF_NAME==design_1_i2s_rx_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_i2s_tx_0_0/design_1_i2s_tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_i2s_tx_0_0 || ORIG_REF_NAME==design_1_i2s_tx_0_0} -quiet] -quiet

# XDC: c:/Users/cargi/Documents/1Fa26/SD/digital_effects_2026-1/digital_effects_2026-1.gen/sources_1/bd/design_1/design_1_ooc.xdc
