domain_path: C:/Users/cargi/Documents/1Fa26/SD/digital_effects_2026-1/sw_workspace_2026-1/platform/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: C:\AMDDesignTools\2026.1\Vitis\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
lang: c
